In [1]:
import numpy as np

# Numpy Data Types


In [2]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

a2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [3]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a1.shape

(3, 3)

In [5]:
a2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
a2.shape

(2, 2, 3)

In [7]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [8]:
a1.ndim

2

In [9]:
import pandas as pd


In [10]:
pd.DataFrame(a1)

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
ones = np.ones((2, 4))

In [12]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
ones.dtype

dtype('float64')

In [14]:
range_array = np.arange(0, 10, 3)
range_array 

array([0, 3, 6, 9])

In [15]:
random = np.random.randint(1, 9, (2, 3))
random

array([[4, 6, 7],
       [5, 5, 3]])

In [16]:
np.random.random((5, 3))

array([[0.201888  , 0.10056163, 0.20348914],
       [0.96545772, 0.83866026, 0.78199037],
       [0.02527051, 0.65881822, 0.07866454],
       [0.39171921, 0.59445692, 0.78880985],
       [0.99784036, 0.47151158, 0.4872172 ]])

In [17]:
np.random.rand(3, 4)

array([[0.06858485, 0.43610918, 0.3299988 , 0.89553674],
       [0.14406163, 0.47035169, 0.07668824, 0.76412788],
       [0.13779402, 0.81623379, 0.50875954, 0.16793772]])

In [18]:
np.random.rand(5,6)

array([[0.67933768, 0.67906727, 0.73011925, 0.35442688, 0.6574383 ,
        0.08180677],
       [0.49834831, 0.46140713, 0.86110116, 0.61567526, 0.59454337,
        0.71900144],
       [0.91175158, 0.78230226, 0.53381854, 0.70384573, 0.57390002,
        0.68818988],
       [0.20702479, 0.08738437, 0.02867612, 0.80452794, 0.71447446,
        0.29463153],
       [0.83742667, 0.91567287, 0.89589707, 0.42831656, 0.88021684,
        0.41361086]])

In [19]:
np.random.seed(77)
np.random.randint(1, 10, (2, 3))

array([[8, 5, 5],
       [6, 9, 1]])

In [20]:
np.random.seed(77)
np.random.randint(1, 10, (2, 3))

array([[8, 5, 5],
       [6, 9, 1]])

In [21]:
a1 = np.random.randint(1,10, 3)
a1

array([8, 6, 4])

In [22]:
a2 = np.random.randint(1, 10, (2, 3))
a2

array([[1, 7, 5],
       [7, 5, 6]])

In [23]:
a3 = np.random.randint(1, 10, (2, 3, 3))
a3

array([[[8, 4, 2],
        [2, 7, 5],
        [6, 9, 2]],

       [[9, 2, 7],
        [4, 5, 4],
        [1, 9, 6]]])

In [24]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [25]:
np.unique(a1)

array([4, 6, 8])

In [26]:
np.unique(a2)

array([1, 5, 6, 7])

In [27]:
np.unique(a3)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [28]:
a3[ 0:, 0:2, 0:2]

array([[[8, 4],
        [2, 7]],

       [[9, 2],
        [4, 5]]])

In [29]:
a3.size

18

# Manupulating Arrays

In [30]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [31]:
np.random.seed(77)
random_nums = np.random.randint(1, 5, 3)
random_nums

array([4, 4, 1])

In [32]:
random_nums + ones

array([5., 5., 2.])

In [33]:
np.random.seed(77)
random_nums_2 = np.random.randint(1, 9, 4)
random_nums_2

array([8, 8, 5, 5])

In [34]:
random_mul_nums = np.random.randint(1, 9, (4, 4))
random_mul_nums

array([[4, 6, 1, 8],
       [1, 2, 8, 6],
       [5, 4, 1, 4],
       [7, 5, 7, 5]])

In [35]:
random_mul_nums * random_nums_2

array([[32, 48,  5, 40],
       [ 8, 16, 40, 30],
       [40, 32,  5, 20],
       [56, 40, 35, 25]])

In [36]:
a1

array([8, 6, 4])

In [37]:
a1.sum()

18

In [38]:
massive_array = np.random.random(10000)


In [39]:
%timeit sum(massive_array)
%timeit np.sum(massive_array) 

780 µs ± 28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.32 µs ± 55.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
a3

array([[[8, 4, 2],
        [2, 7, 5],
        [6, 9, 2]],

       [[9, 2, 7],
        [4, 5, 4],
        [1, 9, 6]]])

In [41]:
a3.std(0)

array([[0.5, 1. , 2.5],
       [1. , 1. , 0.5],
       [2.5, 0. , 2. ]])

# Reshaping and Transpoce

In [42]:
a1

array([8, 6, 4])

In [43]:
a2

array([[1, 7, 5],
       [7, 5, 6]])

In [44]:
a3

array([[[8, 4, 2],
        [2, 7, 5],
        [6, 9, 2]],

       [[9, 2, 7],
        [4, 5, 4],
        [1, 9, 6]]])

In [45]:
a1.reshape((1,3))

array([[8, 6, 4]])

In [46]:
a2.reshape(2,3,1)

array([[[1],
        [7],
        [5]],

       [[7],
        [5],
        [6]]])

In [47]:
a2

array([[1, 7, 5],
       [7, 5, 6]])

In [48]:
a2.T

array([[1, 7],
       [7, 5],
       [5, 6]])

In [49]:
a1.T

array([8, 6, 4])

In [50]:
 a1

array([8, 6, 4])

In [51]:
a2

array([[1, 7, 5],
       [7, 5, 6]])

In [52]:
a4 = a2.reshape((3, 2))

In [53]:
a1.dot(a4)

array([ 58, 122])

In [54]:
import pandas as pd

In [55]:
np.random.seed(77)
stocks1 = np.random.randint(20, size=(5, 3))

np.random.seed(77)
stocks3 = np.random.randint(20, size=(5, 3))
stocks1, stocks3

(array([[11,  5,  0],
        [ 7, 12, 19],
        [ 0,  4,  4],
        [15, 14, 15],
        [10,  7,  3]]),
 array([[11,  5,  0],
        [ 7, 12, 19],
        [ 0,  4,  4],
        [15, 14, 15],
        [10,  7,  3]]))

In [57]:
stocks3

array([[11,  5,  0],
       [ 7, 12, 19],
       [ 0,  4,  4],
       [15, 14, 15],
       [10,  7,  3]])

In [61]:
np.random.seed(77)
market_values = np.random.randint(10, 50, size=(5, 3))
market_values

array([[33, 41, 30],
       [30, 47, 34],
       [41, 42, 49],
       [29, 42, 46],
       [46, 24, 25]])

In [69]:
import pandas as pd
daily_price_frame = pd.DataFrame(market_values, index=['Mon','Tue', 'Wed', 'Thu', 'Fri'], columns=['Butter 1', 'Butter 2', 'Butter 3'])

In [70]:
daily_price_frame

Butter 1  Butter 2  Butter 3
Mon        33        41        30
Tue        30        47        34
Wed        41        42        49
Thu        29        42        46
Fri        46        24        25

In [58]:
test = np.array([1, 2, 3])
test.reshape((1, 3))

array([[1, 2, 3]])

In [71]:
prices = np.array([200, 300, 500]).reshape((1, 3))
price_frame = pd.DataFrame(prices, index=['Prices'], columns=['butter 1', 'butter 2', 'butter 3'])
price_frame

butter 1  butter 2  butter 3
Prices       200       300       500

In [83]:
total = market_values.dot(prices.T)
daily_price_frame['Total Prices'] = total
daily_price_frame

Butter 1  Butter 2  Butter 3  Total Prices
Mon        33        41        30         33900
Tue        30        47        34         37100
Wed        41        42        49         45300
Thu        29        42        46         41400
Fri        46        24        25         28900